AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NBA Live Scores application infrastructure

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  NBAStatsUrl:
    Type: String
    Default: "https://stats.nba.com/stats"
    Description: "Base URL for the NBA Stats API"
  NBABaseUrl:
    Type: String
    Default: "https://cdn.nba.com/static/json/liveData"
    Description: "Base URL for the NBA API"
  ArtifactsBucketName:
    Type: String
    Description: "Name of the S3 bucket for artifacts"

Resources:
  # DynamoDB Table
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub nba-games-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: gameId
          KeyType: HASH

  # MSK Security Group
  MSKSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MSK cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 9092
          ToPort: 9092
          CidrIp: 0.0.0.0/0  # You might want to restrict this in production
      Tags:
        - Key: Name
          Value: !Sub nba-live-msk-sg-${Environment}

  # MSK Cluster
  MSKCluster:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: !Sub nba-live-kafka-${Environment}
      KafkaVersion: 2.8.1
      NumberOfBrokerNodes: 3
      BrokerNodeGroupInfo:
        InstanceType: kafka.t3.small
        ClientSubnets: !Ref SubnetIds
        SecurityGroups:
          - !Ref MSKSecurityGroup
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: 100
      EncryptionInfo:
        EncryptionInTransit:
          ClientBroker: TLS_PLAINTEXT  # Allow both TLS and plaintext
          InCluster: true
      # Add configuration for easier debugging
      LoggingInfo:
        BrokerLogs:
          CloudWatchLogs:
            Enabled: true
            LogGroup: !Sub /aws/msk/nba-live-${Environment}

  # Lambda Functions
  GameUpdateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub nba-game-updates-${Environment}
      Code:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: lambdas/gameUpdateHandler.zip
      Handler: gameUpdateHandler.handler
      Runtime: nodejs18.x
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref GamesTable
          NBA_API_URL: !Ref NBABaseUrl
          MSK_CLUSTER_ARN: !Ref MSKCluster

  GameUpdatePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GameUpdateFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GameUpdateRule.Arn

  BoxScoreFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub nba-box-scores-${Environment}
      Code:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: lambdas/boxScoreHandler.zip
      Handler: boxScoreHandler.handler
      Runtime: nodejs18.x
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref GamesTable
          NBA_API_URL: !Ref NBABaseUrl
          MSK_CLUSTER_ARN: !Ref MSKCluster

  BoxScorePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BoxScoreFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BoxScoreRule.Arn

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub nba-live-api-${Environment}

  GamesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: games

  UpdateResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref GamesResource
      PathPart: update

  BoxScoreResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref GamesResource
      PathPart: "{gameId}"

  BoxScoreMethodResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref BoxScoreResource
      PathPart: boxscore

  # EventBridge Rules
  GameUpdateRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub nba-game-updates-${Environment}
      Description: "Trigger game updates every 30 seconds"
      ScheduleExpression: "rate(30 seconds)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt GameUpdateFunction.Arn
          Id: "GameUpdateFunction"

  BoxScoreRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub nba-box-scores-${Environment}
      Description: "Process game updates for box scores"
      EventPattern:
        source: ["nba-live-updates"]
        detail-type: ["GAME_UPDATE"]
      State: ENABLED
      Targets:
        - Arn: !GetAtt BoxScoreFunction.Arn
          Id: "BoxScoreFunction"

  # API Gateway Methods
  UpdateMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref UpdateResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GameUpdateFunction.Arn}/invocations

  BoxScoreMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref BoxScoreMethodResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BoxScoreFunction.Arn}/invocations

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [UpdateMethod, BoxScoreMethod]
    Properties:
      RestApiId: !Ref ApiGateway

  # API Gateway Stage
  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiDeployment
      StageName: !Ref Environment

  # IAM Roles and Policies
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub nba-lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub nba-lambda-policy-${Environment}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt GamesTable.Arn
              - Effect: Allow
                Action:
                  - kafka:DescribeCluster
                  - kafka:GetBootstrapBrokers
                  - kafka:ListTopics
                Resource: !GetAtt MSKCluster.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/msk/*

  # API Gateway Lambda Permissions
  GameUpdateApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GameUpdateFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*

  BoxScoreApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BoxScoreFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*

Outputs:
  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref GamesTable
  MSKClusterArn:
    Description: ARN of the MSK cluster
    Value: !Ref MSKCluster
  GameUpdateFunctionArn:
    Description: ARN of the Game Update Lambda function
    Value: !GetAtt GameUpdateFunction.Arn
  BoxScoreFunctionArn:
    Description: ARN of the Box Score Lambda function
    Value: !GetAtt BoxScoreFunction.Arn
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment} 