AWSTemplateFormatVersion: '2010-09-09'
Description: NBA Live Scores application infrastructure

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # DynamoDB Tables
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-games-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: gameId
          KeyType: HASH

Outputs:
  GamesTableName:
    Description: Name of the Games DynamoDB table
    Value: !Ref GamesTable
    Export:
      Name: !Sub '${AWS::StackName}-games-table-${Environment}' 